//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidoHR.WebApi.Repository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Designation
    {
        public System.Guid EMP_DesId { get; set; }
        public string DesignationName { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
        public string Createdby { get; set; }
    }
}
