//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidoHR.WebApi.Repository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public System.Guid EmpId { get; set; }
        public string EmpCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Designation { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Createdby { get; set; }
    }
}
