//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidoHR.WebApi.Repository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPayroll
    {
        public System.Guid EmpPRID { get; set; }
        public System.Guid EmpID { get; set; }
        public Nullable<decimal> basic { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> conveyance { get; set; }
        public Nullable<decimal> Adhoc_allow { get; set; }
        public Nullable<decimal> PF_by_bank { get; set; }
        public Nullable<decimal> PF_by_emp { get; set; }
        public Nullable<decimal> Professional_tax { get; set; }
        public Nullable<decimal> Festival_advance { get; set; }
        public bool HG_Insurance { get; set; }
        public bool LIC { get; set; }
        public Nullable<decimal> Net_Pay { get; set; }
        public Nullable<System.DateTime> Date_created { get; set; }
        public string Createdby { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
